repo: https://chromium.googlesource.com/angle/angle.git
ver: chromium/5672
tag_prefix: ''
tag_dot2ul: false
cb_tool: gn
config_options_unix: ''
config_options_embed: ''
config_options_msw: is_debug=false is_clang=false treat_warnings_as_errors=false angle_enable_vulkan=false angle_enable_gl=false
