repo: https://www.openssl.org/source/openssl-3.0.9.tar.gz
ver: 3.0.9
tag_prefix: openssl-
tag_dot2ul: false
cb_tool: perl
config_options_unix: no-tests no-comp no-async no-shared
config_options_embed: no-dso no-engine no-hw
config_options_msw: no-tests no-comp
